<a href="https://colab.research.google.com/github/gmm/RDKit-on-Colab/blob/main/AutoGrid_on_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to Compile AutoGrid 4 on Google Colab

First, we need to get the source code:

In [1]:
!wget https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz
!tar xvf autodocksuite-4.2.6-src.tar.gz

--2022-07-01 15:35:23--  https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/autodocksuite-4.2.6-src.tar.gz
Resolving autodock.scripps.edu (autodock.scripps.edu)... 192.26.252.19
Connecting to autodock.scripps.edu (autodock.scripps.edu)|192.26.252.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35438010 (34M) [application/x-gzip]
Saving to: ‘autodocksuite-4.2.6-src.tar.gz’

autodocksuite-4.2.6 100%[===================>]  33.80M  13.8MB/s    in 2.4s    

2022-07-01 15:35:26 (13.8 MB/s) - ‘autodocksuite-4.2.6-src.tar.gz’ saved [35438010/35438010]

src/README
src/RELEASENOTES
src/autodock/
src/autodock/AD4.1_bound.dat
src/autodock/AD4.1_compact.dat
src/autodock/AD4.1_extended.dat
src/autodock/AD4_PARM99.dat
src/autodock/AD4_parameters.dat
src/autodock/AUTHORS
src/autodock/COPYING
src/autodock/INSTALL
src/autodock/Makefile.am
src/autodock/README
src/autodock/NOTES_xml.txt
src/autodock/PDBQT_tokens.h
src/autodock/RELEASENOTES
src/autodock/alea.cc
sr

In [2]:
%cd /content/src/autogrid
%ls

/content/src/autogrid
aclocal.m4                  copyfilesfromAD   Makefile.in
atom_parameter_manager.cpp  COPYING           missing
atom_parameter_manager.h    depcomp           parameters.h
AUTHORS                     distdepdiel.cpp   parm.h
autogrid.h                  distdepdiel.h     parsetypes.cpp
banner.cpp                  gpfparser.cpp     prHMSfixed.cpp
calc_vina_potential.cpp     gpftoken.h        prototypes.h
calc_vina_potential.h       grid.h            README
check_size.cpp              gridmap.h         setflags.cpp
config.guess                init_gridmap.cpp  strindex.cpp
config.sub                  INSTALL           Tests/
configure*                  install-sh*       times.h
configure.ac*               main.cpp          typedefs.h
configure-universalDarwin*  makecheck         util.cpp
convertmap.cpp              Makefile.am       util.h


In [3]:
# We need csh to generate the default_parameters.h file, and 
# to copy over some source code from AutoDock 4:
!apt-get install csh

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  csh
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 243 kB of archives.
After this operation, 358 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 csh amd64 20110502-3ubuntu0.18.04.1 [243 kB]
Fetched 243 kB in 2s (142 kB/s)
Selecting previously unselected package csh.
(Reading database ... 155639 files and directories currently installed.)
Preparing to unpack .../csh_20110502-3ubuntu0.18.04.1_amd64.deb ...
Unpacking csh (20110502-3ubuntu0.18.04.1) ...
Setting up csh (20110502-3ubuntu0.18.04.1) ...
update-alternatives: using /bin/bsd-csh to provide /bin/csh (csh) in auto mode
Processing triggers for man-db (2.8.3-2ubuntu0.1)

In [4]:
# Now configure the platform-specific Makefile:
!./configure

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking depen

In [6]:
# For some reason, we have to explicitly copy over files from AutoDock 4 source:
!sh copyfilesfromAD

In [7]:
# We also have to create the default_paramters.h file explicitly:
!make default_parameters.h

rm -f default_parameters.h
csh ./../autodock/paramdat2h.csh ./../autodock/AD4_parameters.dat  ./../autodock/AD4.1_bound.dat > default_parameters.h
sh ./copyfilesfromAD


## Edit the Makefile to use Python 2

Note that the "test" target in the Makefile calls "python" but it assumes this is a Python 2-based interpreter!

We need to edit the Makefile, replacing all calls to "python" by "python2".

In [8]:
!sed -i 's/python/python2/' Makefile

## Make AutoGrid

In [9]:
!make test

g++ -DPACKAGE_NAME=\"autogrid\" -DPACKAGE_TARNAME=\"autogrid\" -DPACKAGE_VERSION=\"4.2.6\" -DPACKAGE_STRING=\"autogrid\ 4.2.6\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE_URL=\"\" -DPACKAGE=\"autogrid\" -DVERSION=\"4.2.6\" -DHAVE_LIBM=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_GETPID=1 -DHAVE_FCHMOD=1 -DHAVE_SETLINEBUF=1 -DHAVE_SYSCONF=1 -DHAVE_TIMES=1 -DHAVE_GETRUSAGE=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1 -I.  -Wall -O3 -I . -I./../autodock -Wno-write-strings -DUSE_8A_NBCUTOFF -DUSE_DOUBLE   -g -O2 -MT autogrid4-main.o -MD -MP -MF .deps/autogrid4-main.Tpo -c -o autogrid4-main.o `test -f 'main.cpp' || echo './'`main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:214:5: warning: variable ‘parameter_library_found’

In [10]:
!./autogrid4 --version

AutoGrid 4.2.6   
compilation options:
  Double-precision calculations (USE_DOUBLE):  yes
  Non-bond cutoff for internal energy calculation (NBC): 8.00
  Optimize internal energy scoring (USE_8A_NBCUTOFF):  yes
  Maximum number of receptor atom types (NUM_RECEPTOR_TYPES): 20
  Maximum number of atom types (MAX_ATOM_TYPES): 14
  Maximum number of maps (MAX_MAPS): 16
  Maximum dimension of map x, y, or z (MAX_GRID_PTS): 1025
  Size of int 4, long 8, float 4, double 8, Real 8 bytes.

 Copyright (C) 2009 The Scripps Research Institute.
 License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>
 This is free software: you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.


In [11]:
%ls -ls Tests

total 412
  8 -r--r--r-- 1 124 systemd-network   7003 Apr 24  2012 AD4.1_bound.dat
  4 -r--r--r-- 1 124 systemd-network   1064 Jun 26  2008 hsg1_no_receptor_types.gpf
144 -r--r--r-- 1 124 systemd-network 147416 May 28  2004 hsg1.pdbqt
  4 -r--r--r-- 1 124 systemd-network   1122 Jun 26  2008 hsg1_sm.gpf
  4 -r--r--r-- 1 124 systemd-network   1122 Jun 26  2008 hsg1_sm_minus_two_types.gpf
  4 -r--r--r-- 1 124 systemd-network   1279 Oct  9  2013 hsg1_sm_nbpcoeffs.gpf
  4 -r--r--r-- 1 124 systemd-network   1211 Oct  9  2013 hsg1_sm_nbpreps.gpf
  4 -r--r--r-- 1 124 systemd-network   1181 Oct  9  2013 hsg1_sm_nbpreps_illegal_atom.gpf
  4 -r--r--r-- 1 124 systemd-network   1182 Oct  9  2013 hsg1_sm_nbpreps_toofew.gpf
  4 -r--r--r-- 1 124 systemd-network   1054 Jul 13  2006 hsg1_sm_no_parameter_file.gpf
 12 -r--r--r-- 1 124 systemd-network  12132 Jul 19  2006 hsg1_sm.pdbqt
  4 -r--r--r-- 1 124 systemd-network   1043 Jun 26  2008 py_hsg1_sm.A.map
  4 -r--r--r-- 1 124 systemd-network   1043 Jun 2

In [12]:
!mkdir tmp

In [13]:
!cp Tests/* tmp

In [14]:
%cd tmp

/content/src/autogrid/tmp


In [15]:
%ls

AD4.1_bound.dat                   py_hsg1_sm.d.map
hsg1_no_receptor_types.gpf        py_hsg1_sm.e.map
hsg1.pdbqt                        py_hsg1_sm.HD.map
hsg1_sm.gpf                       py_hsg1_sm.NA.map
hsg1_sm_minus_two_types.gpf       py_hsg1_sm.N.map
hsg1_sm_nbpcoeffs.gpf             py_hsg1_sm.OA.map
hsg1_sm_nbpreps.gpf               test_autogrid4.py
hsg1_sm_nbpreps_illegal_atom.gpf  write_python_maps.py
hsg1_sm_nbpreps_toofew.gpf        x1hpv_CASE0.gpf
hsg1_sm_no_parameter_file.gpf     x1hpv_CASE1.gpf
hsg1_sm.pdbqt                     x1hpv_CASE2.gpf
py_hsg1_sm.A.map                  x1hpv_CASE3.gpf
py_hsg1_sm.C.map                  x1hpv.pdbqt


In [16]:
!sed -i 's/npts 4 4 4/npts 2 4 6/' hsg1_sm.gpf
!head hsg1_sm.gpf

parameter_file AD4.1_bound.dat      # force field default parm file
npts 2 4 6                          # num.grid points in xyz
gridfld hsg1_sm.maps.fld            # grid_data_file
spacing 0.375                       # spacing(A)
receptor_types A C HD N NA OA SA    # receptor atom types
ligand_types A C HD N NA OA         # ligand atom type
receptor hsg1_sm.pdbqt              # macromolecule
gridcenter 2.5 6.5 -7.5             # xyz-coordinates or auto
smooth 0.5                          # store minimum energy w/in rad(A)
map hsg1_sm.A.map                   # atom-specific affinity map


In [17]:
!../autogrid4 -p hsg1_sm.gpf -l hsg_sm_gmm.glg

In [18]:
%ls -lstra

total 540
  4 drwxrwsrwx 6  124 systemd-network   4096 Jul  1 15:36 ../
144 -r--r--r-- 1 root systemd-network 147416 Jul  1 15:36 hsg1.pdbqt
  4 -r--r--r-- 1 root systemd-network   1064 Jul  1 15:36 hsg1_no_receptor_types.gpf
  8 -r--r--r-- 1 root systemd-network   7003 Jul  1 15:36 AD4.1_bound.dat
  4 -r--r--r-- 1 root systemd-network   1043 Jul  1 15:36 py_hsg1_sm.N.map
  4 -r--r--r-- 1 root systemd-network   1043 Jul  1 15:36 py_hsg1_sm.NA.map
  4 -r--r--r-- 1 root systemd-network    973 Jul  1 15:36 py_hsg1_sm.HD.map
  4 -r--r--r-- 1 root systemd-network   1043 Jul  1 15:36 py_hsg1_sm.e.map
  4 -r--r--r-- 1 root systemd-network    918 Jul  1 15:36 py_hsg1_sm.d.map
  4 -r--r--r-- 1 root systemd-network   1043 Jul  1 15:36 py_hsg1_sm.C.map
  4 -r--r--r-- 1 root systemd-network   1043 Jul  1 15:36 py_hsg1_sm.A.map
 12 -r--r--r-- 1 root systemd-network  12132 Jul  1 15:36 hsg1_sm.pdbqt
  4 -r--r--r-- 1 root systemd-network   1054 Jul  1 15:36 hsg1_sm_no_parameter_file.gpf
  4 -r--r--r-

# Example Grid Map

```
ID_PARAMETER_FILE hsg1_sm.gpf
GRID_DATA_FILE hsg1_sm.maps.fld
MACROMOLECULE hsg1_sm.pdbqt
SPACING 0.375
NELEMENTS 2 4 6
CENTER 2.500 6.500 -7.500
-0.226
-0.228
-0.234
-0.247
-0.246
-0.247
-0.283
-0.280
```

AutoDock uses readmap to read in AutoGrid maps; it loops over z, then y, then x fastest:

```
    for ( k = 0;  k < info->num_points1[Z];  k++) {
        for ( j = 0;  j < info->num_points1[Y];  j++) {
            for ( i = 0;  i < info->num_points1[X];  i++) {
		            float thisval;
	              if (fgets( map_line, LINE_LEN, map_file) == NULL) continue; // eof or error
                if (B_charMap) {
                    if (sscanf( map_line,  "%c",  &C_mapValue ) != 1) continue;
		                thisval=mapc2f(C_mapValue);
                } else {
                    if( sscanf( map_line,  "%f",  &thisval) != 1) continue;
                }
		            SetMap(map,info,k,j,i,num_maps,thisval);
		            map_max = max( map_max, thisval );
                map_min = min( map_min, thisval );
                map_total += thisval;
		            nv++;
            }
        }
    }

```

In [19]:
with open('hsg1_sm.C.map', 'r') as f:
  map = f.readlines()

import pprint
pprint.pprint(map[0:10])

['GRID_PARAMETER_FILE hsg1_sm.gpf\n',
 'GRID_DATA_FILE hsg1_sm.maps.fld\n',
 'MACROMOLECULE hsg1_sm.pdbqt\n',
 'SPACING 0.375\n',
 'NELEMENTS 2 4 6\n',
 'CENTER 2.500 6.500 -7.500\n',
 '-0.226\n',
 '-0.228\n',
 '-0.234\n',
 '-0.247\n']


In [20]:
X,Y,Z = [int(n)+1 for n in map[4].split()[1:]]
print(f'X={X} Y={Y}, Z={Z}')

X=3 Y=5, Z=7


In [21]:
for k in range(Z):
  for j in range(Y):
    for i in range(X):
      print(f'i={i}, j={j}, k={k}')

i=0, j=0, k=0
i=1, j=0, k=0
i=2, j=0, k=0
i=0, j=1, k=0
i=1, j=1, k=0
i=2, j=1, k=0
i=0, j=2, k=0
i=1, j=2, k=0
i=2, j=2, k=0
i=0, j=3, k=0
i=1, j=3, k=0
i=2, j=3, k=0
i=0, j=4, k=0
i=1, j=4, k=0
i=2, j=4, k=0
i=0, j=0, k=1
i=1, j=0, k=1
i=2, j=0, k=1
i=0, j=1, k=1
i=1, j=1, k=1
i=2, j=1, k=1
i=0, j=2, k=1
i=1, j=2, k=1
i=2, j=2, k=1
i=0, j=3, k=1
i=1, j=3, k=1
i=2, j=3, k=1
i=0, j=4, k=1
i=1, j=4, k=1
i=2, j=4, k=1
i=0, j=0, k=2
i=1, j=0, k=2
i=2, j=0, k=2
i=0, j=1, k=2
i=1, j=1, k=2
i=2, j=1, k=2
i=0, j=2, k=2
i=1, j=2, k=2
i=2, j=2, k=2
i=0, j=3, k=2
i=1, j=3, k=2
i=2, j=3, k=2
i=0, j=4, k=2
i=1, j=4, k=2
i=2, j=4, k=2
i=0, j=0, k=3
i=1, j=0, k=3
i=2, j=0, k=3
i=0, j=1, k=3
i=1, j=1, k=3
i=2, j=1, k=3
i=0, j=2, k=3
i=1, j=2, k=3
i=2, j=2, k=3
i=0, j=3, k=3
i=1, j=3, k=3
i=2, j=3, k=3
i=0, j=4, k=3
i=1, j=4, k=3
i=2, j=4, k=3
i=0, j=0, k=4
i=1, j=0, k=4
i=2, j=0, k=4
i=0, j=1, k=4
i=1, j=1, k=4
i=2, j=1, k=4
i=0, j=2, k=4
i=1, j=2, k=4
i=2, j=2, k=4
i=0, j=3, k=4
i=1, j=3, k=4
i=2, j

In [22]:
import numpy as np

In [23]:
values = np.array([float(v) for v in map[6:]]) # first 6 lines = header

In [24]:
values

array([-0.226, -0.228, -0.234, -0.247, -0.246, -0.247, -0.283, -0.28 ,
       -0.274, -0.32 , -0.32 , -0.311, -0.358, -0.358, -0.351, -0.225,
       -0.226, -0.229, -0.244, -0.247, -0.247, -0.285, -0.283, -0.279,
       -0.328, -0.328, -0.318, -0.371, -0.368, -0.359, -0.224, -0.223,
       -0.227, -0.243, -0.243, -0.245, -0.283, -0.286, -0.279, -0.333,
       -0.33 , -0.322, -0.374, -0.373, -0.361, -0.221, -0.222, -0.227,
       -0.238, -0.241, -0.244, -0.28 , -0.279, -0.274, -0.329, -0.328,
       -0.319, -0.37 , -0.367, -0.359, -0.219, -0.22 , -0.228, -0.237,
       -0.239, -0.241, -0.273, -0.275, -0.275, -0.32 , -0.318, -0.31 ,
       -0.357, -0.355, -0.344, -0.215, -0.219, -0.226, -0.231, -0.233,
       -0.24 , -0.265, -0.27 , -0.273, -0.305, -0.307, -0.299, -0.342,
       -0.336, -0.328, -0.214, -0.217, -0.225, -0.227, -0.229, -0.24 ,
       -0.252, -0.26 , -0.264, -0.29 , -0.293, -0.29 , -0.319, -0.315,
       -0.314])

In [25]:
print(values.shape)

(105,)


In [26]:
gridmap = values.reshape(Z, Y, X)  # Z sheets, each sheet has Y lists, each X long. 
print(gridmap.shape) # 7 sheets, 5 lists, each 3 long.
print(gridmap)

(7, 5, 3)
[[[-0.226 -0.228 -0.234]
  [-0.247 -0.246 -0.247]
  [-0.283 -0.28  -0.274]
  [-0.32  -0.32  -0.311]
  [-0.358 -0.358 -0.351]]

 [[-0.225 -0.226 -0.229]
  [-0.244 -0.247 -0.247]
  [-0.285 -0.283 -0.279]
  [-0.328 -0.328 -0.318]
  [-0.371 -0.368 -0.359]]

 [[-0.224 -0.223 -0.227]
  [-0.243 -0.243 -0.245]
  [-0.283 -0.286 -0.279]
  [-0.333 -0.33  -0.322]
  [-0.374 -0.373 -0.361]]

 [[-0.221 -0.222 -0.227]
  [-0.238 -0.241 -0.244]
  [-0.28  -0.279 -0.274]
  [-0.329 -0.328 -0.319]
  [-0.37  -0.367 -0.359]]

 [[-0.219 -0.22  -0.228]
  [-0.237 -0.239 -0.241]
  [-0.273 -0.275 -0.275]
  [-0.32  -0.318 -0.31 ]
  [-0.357 -0.355 -0.344]]

 [[-0.215 -0.219 -0.226]
  [-0.231 -0.233 -0.24 ]
  [-0.265 -0.27  -0.273]
  [-0.305 -0.307 -0.299]
  [-0.342 -0.336 -0.328]]

 [[-0.214 -0.217 -0.225]
  [-0.227 -0.229 -0.24 ]
  [-0.252 -0.26  -0.264]
  [-0.29  -0.293 -0.29 ]
  [-0.319 -0.315 -0.314]]]


In [27]:
print(gridmap.shape)

(7, 5, 3)


In [28]:
k=-1
for sheet in gridmap:
  k = k + 1
  print(sheet)
  j = -1
  for row in sheet:
    (print(row))
    j = j + 1
    i = -1
    for value in row:
      i = i + 1
      print(i, j, k, value)

[[-0.226 -0.228 -0.234]
 [-0.247 -0.246 -0.247]
 [-0.283 -0.28  -0.274]
 [-0.32  -0.32  -0.311]
 [-0.358 -0.358 -0.351]]
[-0.226 -0.228 -0.234]
0 0 0 -0.226
1 0 0 -0.228
2 0 0 -0.234
[-0.247 -0.246 -0.247]
0 1 0 -0.247
1 1 0 -0.246
2 1 0 -0.247
[-0.283 -0.28  -0.274]
0 2 0 -0.283
1 2 0 -0.28
2 2 0 -0.274
[-0.32  -0.32  -0.311]
0 3 0 -0.32
1 3 0 -0.32
2 3 0 -0.311
[-0.358 -0.358 -0.351]
0 4 0 -0.358
1 4 0 -0.358
2 4 0 -0.351
[[-0.225 -0.226 -0.229]
 [-0.244 -0.247 -0.247]
 [-0.285 -0.283 -0.279]
 [-0.328 -0.328 -0.318]
 [-0.371 -0.368 -0.359]]
[-0.225 -0.226 -0.229]
0 0 1 -0.225
1 0 1 -0.226
2 0 1 -0.229
[-0.244 -0.247 -0.247]
0 1 1 -0.244
1 1 1 -0.247
2 1 1 -0.247
[-0.285 -0.283 -0.279]
0 2 1 -0.285
1 2 1 -0.283
2 2 1 -0.279
[-0.328 -0.328 -0.318]
0 3 1 -0.328
1 3 1 -0.328
2 3 1 -0.318
[-0.371 -0.368 -0.359]
0 4 1 -0.371
1 4 1 -0.368
2 4 1 -0.359
[[-0.224 -0.223 -0.227]
 [-0.243 -0.243 -0.245]
 [-0.283 -0.286 -0.279]
 [-0.333 -0.33  -0.322]
 [-0.374 -0.373 -0.361]]
[-0.224 -0.223 -0.22

In [29]:
print(gridmap[5][3][1]) # [z][y][x]

-0.307


# KD-trees

KD-trees can be used to rapidly find the nearest points in a multidimensional space. To find the nearest neighbor, rather than O(N<sup>2</sup>), it is O(log N).

See the SciKit-Learn documenation here: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html

In [30]:
# Query for k-nearest neighbors

from sklearn.neighbors import KDTree

rng = np.random.RandomState(0)

X = rng.random_sample((10, 3))  # 10 points in 3 dimensions

tree = KDTree(X, leaf_size=2)              
dist, ind = tree.query(X[:1], k=3)  
             
print(ind)  # indices of 3 closest neighbors
print(dist)  # distances to 3 closest neighbors

[[0 3 1]]
[[0.         0.19662693 0.29473397]]


In [31]:
# Query for neighbors within a given radius:
print(tree.query_radius(X[:1], r=0.3, count_only=True))
ind = tree.query_radius(X[:1], r=0.3)
print(ind)  # indices of neighbors within distance 0.3

# Compute a gaussian kernel density estimate:
X = rng.random_sample((100, 3))
tree = KDTree(X)                
tree.kernel_density(X[:3], h=0.1, kernel='gaussian')

# Compute a two-point auto-correlation function
X = rng.random_sample((30, 3))
r = np.linspace(0, 1, 5)
tree = KDTree(X)                
tree.two_point_correlation(X, r)

[3]
[array([3, 0, 1])]


array([ 30,  68, 264, 568, 826])

In [32]:
# How much virtual memory is there?

from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 13.6 gigabytes of available RAM

Not using a high-RAM runtime
